### ISSUE TITLE
Please add a license or people cannot really use it.

### ISSUE THREAD

**Issue by Poikilos** [Sarath18/terrain_generator#1]
Having no license legally means "[no permission](https://choosealicense.com/no-permission/)."

Other people may want to improve your program, but will not because of the license.

See [choosealicense.com](https://choosealicense.com/).

You can choose a license on GitHub using the GUI: "Create new file" then name it license.txt -- a menu will appear automatically.

I hope you get this and that you are willing to free your program from these restrictions.

**Comment by Sarath18** [comment]
Apologies for the late reply and thank you for pointing this out. I have added the License to this repository.
